name: steins-middle
services:
  # Elasticsearch + Kibana
  elk:
    container_name: steins-elk
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/sebp/elk:8.17.3
    volumes:
      - ${ELK_VOLUME_DIRECTORY:-./data/elasticsearch}:/var/lib/elasticsearch
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "5044:5044" # Logstash Beats 输入端口
      - "5601:5601" # Kibana 端口
      - "9200:9200" # Elasticsearch HTTP 端口
    deploy:
      resources:
        limits:
          memory: 4096M  # 限制容器最大内存使用量
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - middle-network

  # skywalking oap+ui
  sw-oap:
    container_name: steins-sw-oap
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/skywalking.docker.scarf.sh/apache/skywalking-oap-server:10.3.0
    depends_on:
      elk:
        condition: service_healthy
    environment:
      - TZ=Asia/Shanghai
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=steins-elk:9200
    ports:
      - "11800:11800"
      - "12800:12800"
    restart: unless-stopped
    networks:
      - middle-network

  sw-ui:
    container_name: steins-sw-ui
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/skywalking.docker.scarf.sh/apache/skywalking-ui:10.3.0
    depends_on:
      - sw-oap
    environment:
      - TZ=Asia/Shanghai
      - SW_OAP_ADDRESS=http://steins-sw-oap:12800
    ports:
        - "12880:8080"
    restart: unless-stopped
    networks:
      - middle-network

  mysql:
    container_name: steins-mysql
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mysql:8.0.41
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_VOLUME_LOG:-./data/mysql/logs}:/var/log/mysql
      - ${MYSQL_VOLUME_DATA:-./data/mysql/data}:/var/lib/mysql
      - ${MYSQL_VOLUME_CONF:-./data/mysql/conf}:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    networks:
      - middle-network


  mongodb:
    container_name: steins-mongodb
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mongo:8.0.9
    ports:
      - "27017:27017"
    volumes:
      - ${MONGODB_VOLUME_DIRECTORY:-.}:/data/db
    restart: unless-stopped
    networks:
      - middle-network

  redis:
    container_name: steins-redis
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/redis:5.0.14
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_VOLUME_DIRECTORY:-.}:/data
      - ${REDIS_VOLUME_CONFIG:-./redis.conf}:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      - middle-network

  nacos:
    container_name: steins-nacos
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nacos/nacos-server:v2.0.3
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      MODE: standalone
    volumes:
      - ${NACOS_VOLUME_CONFIG:-./conf}:/home/nacos/conf/
      - ${NACOS_VOLUME_LOG:-./logs}:/home/nacos/logs
      - ${NACOS_VOLUME_DATA:-./data}:/home/nacos/data
    restart: always
    networks:
      - middle-network

  etcd:
    container_name: steins-milvus-etcd
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${MILVUS_VOLUME_DIRECTORY:-./data/milvus/data}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - middle-network

  minio:
    container_name: steins-milvus-minio
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${MILVUS_VOLUME_DIRECTORY:-./data/milvus/data}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - middle-network

  standalone:
    container_name: steins-milvus-standalone
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/milvusdb/milvus:v2.6.3
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${MILVUS_VOLUME_DIRECTORY:-./data/milvus/data}/volumes/milvus:/var/lib/milvus
      - ${MILVUS_VOLUME_CONFIGS:-./data/milvus/configs}:/milvus/configs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    restart: unless-stopped
    networks:
      - middle-network
networks:
  middle-network:
    driver: bridge
